---
title: "Chapter_7.9"
author: "Ruben J, Hermann"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Hmsc)
library(ape)
library(MASS)
library(tidyverse)
library(bayesplot)
library(corrplot)
```


## 7.9 Real Case Study with HMSC: Sequencing Data on Dead Wood-Inhabiting Fungi

As a real-data case study, we consider sequencing data on dead wood-inhabiting fungi.

### 7.9.1 The Data and the Ecological Context

```{r}
data = read.csv(file = file.path("Real_Data/Section_7_9_fungi/data","data.csv"))
n = dim(data)[1]
head(data [, 1:6])
#str(data)
data$LogID <- as.factor(data$LogID)
```

```{r}
XData = data.frame(DC = as.factor(data$DC),readcount = data$readcount)
YData = data [, 4:dim(data)[2]]
sel.sp = colSums(YData > 0) >= 10
YData = YData [, sel.sp]
```

```{r}
P = colMeans(YData > 0)
A = colSums(YData)/sum(YData)
```

### 7.9.2 Fitting Six Alternative HMSC Models to the Data

```{r}
studyDesign = data.frame(sample = data$LogID)
rL = HmscRandomLevel(units = studyDesign$sample)
models = list()
for (i in 1:3){
  Y = as.matrix(YData)
  if (i==2) {Y = 1*(Y > 0)}
  if (i==3) {
    Y[Y==0] = NA
    Y = log(Y)
  }
  tmp = list()
  for (j in 1:2){
    XFormula = switch(j, ~1 + log(readcount),~DC +log(readcount))
    m = Hmsc(Y = Y, XData = XData, XFormula = XFormula,    studyDesign = studyDesign, ranLevels =
    list(sample = rL), distr = switch(i,"lognormal poisson","probit","normal"),YScale = TRUE)
    tmp[[j]] = m
  }
  models[[i]] = tmp
}
```

```{r}
nChains = 2
thin = 5
samples = 1000
transient = 500*thin
verbose = 500*thin
```
```{r}
for (i in 1:3){
  for (j in 1:2){
    if(i != 3 & j != 2) {models[[i]][[j]] = sampleMcmc(models[[i]][[j]], thin = thin,
    samples = samples, transient = transient,
    nChains = nChains, verbose = verbose,
    initPar = "fixed effects")}
    if(i == 3 & j == 2) {models[[i]][[j]] = sampleMcmc(models[[i]][[j]], thin = thin,
    samples = samples, transient = transient,
    nChains = nChains, verbose = verbose)
    }
  }
}
```

```{r}
for (i in 1:3){
  mpost = convertToCodaObject(models[[i]][[2]])
  psrf.beta = gelman.diag(mpost$Beta,
  multivariate = FALSE)$psrf
  psrf.omega = gelman.diag(mpost$Omega[[1]],
  multivariate = FALSE)$psrf
}
```

### 7.9.3 Inference on Abiotic and Biotic Species Niches

```{r}
m = models[[2]][[2]]
Gradient = constructGradient(m, focalVariable = "DC",
non.focalVariables = list("readcount" = list(1)))
predY = predict(m, Gradient = Gradient, expected = TRUE)
```

```{r}
for (i in 1:3){
    for (j in 1:2){
        OmegaCor = computeAssociations(models[[i]][[j]])
        supportLevel = 0.95
        toPlot = ((OmegaCor[[1]]$support > supportLevel)
        + (OmegaCor[[1]]$support < (1-supportLevel))> 0) * OmegaCor[[1]]$mean
        corrplot(toPlot, method = "color",col = c("grey","white","black"))
    }
}
```

### 7.9.4 Latent Variables as Model-Based Ordination

```{r}
for (j in 1:2){
  m = models[[2]][[j]]
  biPlot(m, etaPost = getPostEstimate(m, "Eta"),
  lambdaPost = getPostEstimate(m, "Lambda"), colVar = 2)
}
```
